version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ~/home/kevnnard/databases/API_MKP/postgres_data:/var/lib/postgresql/data
